version: '{build}'
image: Visual Studio 2019
skip_commits:
  files:
    - '*.md'
    - '*.txt'
    - '.editorconfig'
    - lic/*
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
install:
- ps: Install-Product node 6
- npm install -g eclint
- git rm .editorconfig
- eclint check -n "**/*.{cs,tt,cmd,sh,md,txt,yml}"
- eclint check -w "**/*.{cs,tt,cmd,sh,md,txt,yml,json,sln,csproj,shfbproj}"
- git reset --hard
- ps: tools\dotnet-install.ps1 -JSonFile global.json
before_build:
- dotnet --info
build_script:
- ps: >-
    grep --extended-regexp '^[[:space:]]*using[[:space:]]+System\.Linq;' (dir MoreLinq.Test\*Test.cs)

    if ($LASTEXITCODE -eq 0) {
        throw 'Unit tests should not import System.Linq'
    }

    $id = $env:APPVEYOR_REPO_COMMIT_TIMESTAMP -replace '([-:]|\.0+Z)', ''

    $id = $id.Substring(0, 13)

    cmd /c call pack.cmd ci-$id

    if ($LASTEXITCODE -ne 0) {
        throw "Building/Packing failed with an exit code of $LASTEXITCODE."
    }

    $diff = git diff --ignore-all-space --exit-code 2>&1

    $diff | % { if ($_ -is [string]) { $_ } else { [string]$_ } } | echo

    if ($LASTEXITCODE -ne 0) {
        throw "New code was generated during build that's not been committed."
    }
# Download the latest version of WhiteSource FS Agent
- curl -LJO https://github.com/whitesource/fs-agent-distribution/raw/master/standAlone/whitesource-fs-agent.jar
# Download the default configuration file
- curl -LJO https://github.com/whitesource/fs-agent-distribution/raw/master/standAlone/whitesource-fs-agent.config
# Replace the flags in the configuration to enable policy check
- cat whitesource-fs-agent.config | sed -e "s/forceCheckAllDependencies=false/forceCheckAllDependencies=true/" > temp_file.config
# Copy the new configuration file over the original file
- mv temp_file.config whitesource-fs-agent.config
# Run WhiteSource FS Agent
- java -jar whitesource-fs-agent.jar -apiKey 41c71f81b00e4ec5868fece050113260fa23031c6fac460a81945a99bfaeea51 -product mytest -c whitesource-fs-agent.config -d . -project MoreLINQ
test_script:
- cmd: test.cmd
- ps: dotnet reportgenerator -reports:MoreLinq.Test/coverage.netcoreapp3.1.opencover.xml -targetdir:tmp/cover -tag:(git show -q --pretty=%H)
- ps: Get-ChildItem tmp/cover | Compress-Archive -DestinationPath coverage-report.zip
- cmd: |
    cd tmp\cover
    tar -cvz -f ../../coverage-report.tar.gz *
artifacts:
- path: dist\*.nupkg
- path: coverage-report.*
deploy:
- provider: NuGet
  server: https://www.myget.org/F/morelinq/api/v2/package
  api_key:
    secure: fhGwXyO35FSshRzs5GWmF1LJTrd1sIqmS/jNCSfO2LfOciuYAKiXuFMYZFGiTAl+
  symbol_server: https://www.myget.org/F/morelinq/symbols/api/v2/package
  on:
    branch: deploy
notifications:
- provider: Email
  to:
  - morelinq-roll@googlegroups.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
on_success:
- curl -s -o upload https://copilot.blackducksoftware.com/ci/appveyor/scripts/upload
- bash upload
- curl -s https://scripts.scantist.com/staging/scantist-bom-detect.jar --output scantist-bom-detect.jar
- java -jar scantist-bom-detect.jar


